# Generated by Django 3.2.4 on 2021-06-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Price', models.FloatField()),
                ('description', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
